table All_Measure
	lineageTag: f52f0cd0-aa92-475b-a49c-6ada3b23d194

	measure 'Total Users' = DISTINCTCOUNT(Users[User_id])
		formatString: 0
		lineageTag: b42d4e0d-b0ab-438b-91e6-8f997015e00b

	measure 'Total Orders' = COUNTROWS(Orders)
		formatString: 0
		lineageTag: fa87fc34-47bb-420d-ad2b-a3e948cf44ae

	measure 'top10% Customers' = CALCULATE(SUM(Users[totalSales]),FILTER(Users,Users[Rank]<=7793))
		formatString: 0
		lineageTag: d65d7f3a-c8a8-439b-bb24-767b1af07fa4

	measure 'Rating Count' = COUNT(Restaurant[Rating])
		formatString: 0
		lineageTag: 77b6fd87-50e6-4655-bba1-861e2e8bdca6

	measure 'Total Quantity Amount' = SUM(Orders[Value])
		formatString: 0
		lineageTag: 7eb9d03c-35c6-4408-af73-d5332140ab52

	measure 'Dynamic Title Year' = ```
			
			         var selectType = SELECTEDVALUE(Orders[Type])
			         RETURN selectType&" by Year "
			```
		lineageTag: 820b93f6-b50e-4691-9f5e-aefb40e87d13

	measure 'User Count (Orders)' = DISTINCTCOUNT(Orders[User_id])
		formatString: 0
		lineageTag: 1e3dfa01-f04a-4e63-8303-233dcacf08af

	measure 'Current Year' = MAX(Orders[Year])
		lineageTag: a89b1843-204a-44b2-b617-16e4431f8d9c

	measure 'Current YR Sales' = VAR yr = [Current Year] RETURN CALCULATE([Sale Value],Orders[Year]=yr)
		formatString: 0
		lineageTag: 234ae9ae-4460-4471-ba25-3152179cd50c

	measure 'Previous YR' = ([Current Year]-1)
		lineageTag: ff9c641d-b0cd-4371-b0f4-43df86b036b4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Previous YR Sales' = VAR pr_sales = [Previous YR] RETURN CALCULATE([Sale Value], Orders[Year]= pr_sales)
		formatString: 0
		lineageTag: ab664477-d989-44e6-be02-16f359c890e2

	column Column
		formatString: 0
		lineageTag: 0bb2d02b-b596-4f19-9986-386d3523b0a7
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition All_Measure = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = a890b17896c847a0aaf1091938183acc

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

